version: '3'

services:
  waystar-frontend:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: ghcr.io/apollo-xiv/waystar-frontend

    ports:
      - "3000:3000"

    env_file:
      - config.env
      - secrets.env
