name: Build CDN Server Image

on:
  workflow_dispatch:
  workflow_call:
    

jobs:

  static:
    permissions: write-all
    name: Build static image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name:  next-static
          path:  cdn/static/
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        run: cd cdn && docker compose -f ./docker-compose.yml build
      - name: Push to GHCR.io
        run: docker push ghcr.io/apollo-xiv/k8s-cdn:latest
