name: Build Frontend Server Image

on:
  workflow_call:
  workflow_dispatch:
    

jobs:

  server:
    permissions: write-all
    name: Build server image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name:  next-server
          path:  frontend/build/standalone
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        run: cd frontend && docker compose -f ./docker/production/docker-compose.yml build
      - name: Push to GHCR.io
        run: docker push ghcr.io/apollo-xiv/waystar-frontend:latest