name: Check Infrastructure Configuration

on:
  workflow_call:

jobs:
  deploy-changes:
    name: deploy changes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: create tfvars
      run: echo '${{ secrets.TFVARS }}' >> terraform.tfvars
    
    - name: Terraform Apply
      uses: sturlabragason/terraform_state_artifact@v1
      with:
        encryptionkey: ${{ secrets.TF_STATE_SECRET }}
    
    # - name: Preserve State
    #   uses: 

    - name: Download kubectl
      run: aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)

    - name: Persist Kubectl
      uses: actions/upload-artifact@v3
      with:
        name: kubeconfig
        path: ~/.kube/config