name: Check Infrastructure Configuration

on:
  workflow_call:

jobs:
  deploy-changes:
    name: deploy changes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: create tfvars
      run: cd infrastructure/terraform && echo '${{ secrets.TFVARS }}' >> terraform.tfvars
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init
      run:  cd infrastructure/terraform && terraform init

    - name: Terraform apply
      run: cd infrastructure/terraform && terraform apply -auto-approve
    
    # - name: Preserve State
    #   uses: 

    - name: Download kubectl
      run: aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)

    - name: Persist Kubectl
      uses: actions/upload-artifact@v3
      with:
        name: kubeconfig
        path: ~/.kube/config