name: Check Infrastructure Configuration

on:
  workflow_call:

jobs:
  deploy-changes:
    name: deploy changes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: create tfvars
      run: cd infrastructure/terraform && echo '${{ secrets.TFVARS }}' >> terraform.tfvars
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init
      run:  cd infrastructure/terraform && terraform init

    - name: Terraform apply
      run: cd infrastructure/terraform && terraform apply -auto-approve

    - name: Commit Plan for Approval
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'Terraform Plan'
        branch: 'Terraform-Plan'
        base: 'main'
        token: ${{ secrets.GITHUB_TOKEN }}