name: Dispatch Jobs on Push to Main

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-infrastructure-config:
    name: Check Infrastructure Configuration
    uses: ./.github/workflows/infrastructure.yml
  
  dispatch-codebase-jobs:
    needs: [check-infrastructure-config]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/next-build.yml