name: Build NextJS project

on:
  # push:
  #   branches: [ "main" ]
  workflow_call:
    
jobs:

  build:
    name: Compile Frontend and CDN

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the NextJS Server
      env:
        BUILD: "true"
      run: cd frontend && npm i && npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: next-server
        path: frontend/build/standalone/
    - uses: actions/upload-artifact@v3
      with:
        name: next-static
        path: frontend/build/static/

  static:
    needs: [build]
    uses: ./.github/workflows/cdn-image.yml


  server:
    needs: [build]
    uses: ./.github/workflows/frontend-image.yml