name: Build NextJS project

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the NextJS Server
      run: cd frontend && npm i && npm run build
